name: Bug Report
description: Create a bug report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating System
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "Ubuntu 23.04"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Plugin Version
      description: "Please provide the plugin version you are using."
      options:
        - VDE Plugin
        - Linux Bridge Plugin
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: "What happened?"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: "Which steps do we need to take to reproduce this error? Attach also a network scenario to reproduce the error."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "A description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the feature request here."
