name: Feature Request
description: Suggest an idea for the network plugin
body:
  - type: markdown
    attributes:
      value: |
        ---
        
        Thank you for contributing to Kathará with new ideas!
  - type: textarea
    id: bug-description
    attributes:
      label: Related Bug
      description: "Is your feature request related to a problem? Please describe."
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: "Why is it a good idea add this feature to the network plugin?"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: "Describe the solution you would like."
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: "Describe alternative solutions you have considered."
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the feature request here."
